### ISSUE TITLE
No code completion when caret is before comma / right paren /...

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#110]
[2023-10-17T16:04:07.712-0400] [INFO] LanguageServerInfo: 1.11.0-d8a93a9 -- ClientInfo: Visual Studio Code 1.83.1

Plugin version is 1.4.23. Issue also appears in 1.4.21.

Of the first 6 options presented, only the highlighted one should be. All of the others are from other methods in the class.

![grafik](https://github.com/vscode-abl/vscode-abl/assets/8291561/d6e41c2e-be51-4862-adce-75c56f028fb3)

**Comment by PeterJudgeZA** [comment]
This might be impacted by the syntax error (missing `:` before the called method name).

**Comment by gquerret** [comment]
Suggestions are provided by VSCode, based on the text in the current buffer, not by the LS. You can deactivate those suggestions with `"editor.wordBasedSuggestions": false` in your settings.
However, the LS should provide CC in this case, but there's a bug when asking for CC when the caret is in the middle of a word and just before a comma. That will be fixed in next release.

**Comment by gquerret** [comment]
Fixed in develop branch
