### ISSUE TITLE
Add a code indentation action

### ISSUE THREAD

**Issue by clement-brodu** [vscode-abl/vscode-abl#129]
One of the last blocking things that we are missing to migrate from PDSOE to vscode is the possibility of automatically indenting the code.

Without this we would have way too many conflicts in git because we have a lot of developers.

Do you plan to implement this feature ?

**Comment by gquerret** [comment]
Code indentation can be very difficult to implement correctly due to the very high number of coding styles. So far, that stayed in the backlog, but that may be re-evaluated.

**Comment by gquerret** [comment]
Closing as won't fix _in this repo_, as it's now clear that code formatter will not make it in the language server.

I've always postponed the implementation of a code parser due to the very high number of options, but after having read https://prettier.io/docs/en/option-philosophy and seen how widespread Prettier is now, it might be a good thing not to allow any option for ABL and just come with one standard. I'll help anybody interested in integrating Proparse into Prettier (or any other tool), but for now I don't have time to take of the implementation myself.

**Comment by mikefechner** [comment]
Maybe this helps: https://github.com/BalticAmadeus/AblFormatter
