### ISSUE TITLE
Auto-complete should also complete namespaces and not only class/interface names

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#220]
I would expect to be able to type "Progress." and get auto-complete suggestions.
If I do that in OEDT I get:

![image](https://github.com/user-attachments/assets/e4c85f28-9d34-4892-90c7-343e5a01b64d)

If I do that in VSCode I get:

![image](https://github.com/user-attachments/assets/5f1cd87a-2063-4448-87bb-dd6bed5594e2)

**Comment by PeterJudgeZA** [comment]
That "using" code completion is very PDSOE-esque 😆

**Comment by gquerret** [comment]
> That "using" code completion is very PDSOE-esque 😆

I don't expect the LS to provide this kind of options. Is that a snippet in your environment?

**Comment by gquerret** [comment]
And regarding the issue, yes, that will be improved

**Comment by lievendf** [comment]
> > That "using" code completion is very PDSOE-esque 😆
> 
> I don't expect the LS to provide this kind of options. Is that a snippet in your environment?

No, none of the 3 presented options are snippets.

**Comment by gquerret** [comment]
> No, none of the 3 presented options are snippets.

Interesting because according to the [icon](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions), this should come from a snippet. Even funnier is that the exact same issue was reported by @PeterJudgeZA some time ago. With the same typo in `routing-level on error ...` in the description of `routine-level...`. As snippets can be provided by extension, I had a look at the other ABL extensions (not a very long list...), and found the snippet: https://github.com/kenherring/ablunit-test-runner/blob/prerelease-0.2.7/snippets/snippets-abl.json#L9
I opened PR kenherring/ablunit-test-runner#201 to fix this typo.

**Comment by lievendf** [comment]
I didn't know snippets could be provided by an extension...
And in this case I would rather not have these presented (they seem a bit out of scope for an ABLUnit Test Runner extension in my opinion).
Is there a way to suppress or exclude these @kenherring ?

**Comment by gquerret** [comment]
Will be included in 1.15.3

<img src="https://uploads.linear.app/0095e3bd-1f0f-4e0f-99c7-6559bb746a08/89780dbe-e14b-484d-9b63-7f7d3b202270/e29378b8-4d2c-4139-8b8a-090179bb42f3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzAwOTVlM2JkLTFmMGYtNGUwZi05OWM3LTY1NTliYjc0NmEwOC84OTc4MGRiZS1lMTRiLTQ4NGQtOWI2My03ZjdkM2IyMDIyNzAvZTI5Mzc4YjgtNGQyYy00MTM5LThiOGEtMDkwMTc5YmI0MmYzIiwiaWF0IjoxNzMyMzcyOTUyLCJleHAiOjMzMzAyOTMyOTUyfQ.oK80hXE7zLRsqyHZtTiW70-DuQUkzqiClLNKhqqrnm4 " alt="image.png" width="504" height="204" />

**Comment by gquerret** [comment]
I lied, that's in 1.15.4 (currently on its way to the marketplace)
