### ISSUE TITLE
SonarLint VSCode - endless stream of "Skipping text document analysis because workspace folder is not synchronized yet" output log entries

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#221]
Hi,

Since there is no SonarLint VSCode issue tracker I'm adding this here.
I just set up the SonarLint ABL plugin and opened a source file in my project, added a line and saved the file.
In the SonarLint Output tab I now see an endless stream of the following entries: (redacted file name)

```
[Info - 16:33:52.554] Skipping text document analysis because workspace folder is not synchronized yet "file:///c:/Workspace/...filename.cls"
[Info - 16:33:52.760] Skipping text document analysis because workspace folder is not synchronized yet "file:///c:/Workspace/...filename.cls"
[Info - 16:33:52.965] Skipping text document analysis because workspace folder is not synchronized yet "file:///c:/Workspace/...filename.cls"
[Info - 16:33:53.170] Skipping text document analysis because workspace folder is not synchronized yet "file:///c:/Workspace/...filename.cls"
...
```

Any idea what's going on and how I can fix this?

**Comment by gquerret** [comment]
> Since there is no SonarLint VSCode issue tracker I'm adding this here.

Absolutely fine.

The endless stream of `Skipping text document` is supposed to be fixed in 4.10, but let me know in this ticket if you still see it in this version.

The new stack trace is part of the changes introduced in 4.10. As this is related to languages (C / C#) that are not part of this customized version of Sonarlint, I'll just deactivate this part and release a new version.
