### ISSUE TITLE
Auto-complete should ignore case for primitives

### ISSUE THREAD

**Issue by lievendf** [vscode-abl/vscode-abl#222]
![Code_i36Myuu9Vl](https://github.com/user-attachments/assets/be013f84-a075-4a09-9e6a-75eb5d802a1b)

Notice how I only get "CHARACTER" proposed when typing in upper case (but still get all "Character*" items as well!), but not when typing "charact...".

**Comment by gquerret** [comment]
I created a few classes starting with `Character`, and tried your example.
![def-var](https://github.com/user-attachments/assets/eb25eaad-c01a-4307-8d4f-1dadf596f4c4)

So I think in your try, `CHARACTER` is present, but after the list of classes. It becomes the first entry in the second try because it matches name and case. Note that this is my guess, as the LS doesn't have full control over the dialog box.
The LS returns an ordered list of entries ; currently, class names have higher priorities than keywords. That may be changed, but I must first evaluate the impact.

**Comment by gquerret** [comment]
Raised priority of datatype keywords only in the completion list.
