### ISSUE TITLE
Can't configure runtime in Linux

### ISSUE THREAD

**Issue by sakrocap** [vscode-abl/vscode-abl#26]
How to configure runtime in Linux environment? 
We have VSCode on Windows and OpenEdge installation is Linux only. 
VSCode is connected to Linux : Connect to host... 

This  configuration below fails with: "'No OpenEdge runtime configured on this machine"
```
"abl.configuration.runtimes": [ {"name": "11.7", "path": "/opt/dlc", "default": true} ]
```
Does this mean that we must have OE installed on Windows machine too?

**Comment by gquerret** [comment]
In a standard VSCode configuration, the language server is executed on the same machine, so you'll need OE running on your Windows machine. Or run VSCode on your Linux machine.
You can have a look at the Dockerfile in this [repo](https://github.com/vscode-abl/vscode-abl/tree/main/docker), which let you have the server side on Linux, and the client on your web browser.
Otherwise, you can have a look at this article from the VSCode blog: https://code.visualstudio.com/blogs/2022/07/07/vscode-server. Not tested, that's on my TODO list.

**Comment by sakrocap** [comment]
Thanks for quick reply!
After installing OE 11.7 Windows version and running Windows-only configuration, this error message disappeared.
Now code completion works somehow. I still have doubts my configuration is not correct as keywords don't appear in uppercase. Setting "abl.completion.upperCase" true or false doesn't seem to have any effect.

Are you planning to include "check syntax" to this extension? 

Thanks for good work so far!

**Comment by gquerret** [comment]
There's no direct "check syntax" link, as everything is built in the background by the language server. Every time you save a procedure or class, it is recompiled in the background. Works with referenced include files too.
You can find logs in the .builder directory, and also in the "Output" view in VSCode  (in ABL Language Server section).

**Comment by gquerret** [comment]
If you don't see a line in the LS log which says `SourceWatcher - Recompile xxxx.p`, then something is wrong in the config.
