### ISSUE TITLE
Tokens have incorrect/inconsistent textmate scopes

### ISSUE THREAD

**Issue by PeterJudgeZA** [vscode-abl/vscode-abl#66]
I'm trying to set up custom colours for syntax highlighting, and am noticing certain of the reported tokens are (to me, anyway) incorrect or at least inconsistent.

Using the Developer: Inspect Editor Tokens and Scopes tool in SHIFT-CTRL-P, I see the following.

1. Block labels are sometimes variable.other.abl and sometimes keyword.other.abl. Ideally they should be ther own type .

![grafik](https://user-images.githubusercontent.com/8291561/228288975-8b7c26c6-eb69-4ea8-bc9a-bd68e09803c6.png)

![grafik](https://user-images.githubusercontent.com/8291561/228289016-81fa26d8-dee7-4d32-82f9-50e61670dcee.png)

2.  The `AS` in a method's parameter declaration is variable.other.abl (instead of , I'd guess, keyword.other.abl).
![grafik](https://user-images.githubusercontent.com/8291561/228289241-3f72d979-57fe-4d07-ae6a-865d062f4a61.png)

3. Type names are sometimes support.function.abl and sometimes variable.other.abl 

![grafik](https://user-images.githubusercontent.com/8291561/228290716-9a4b0e48-ef51-4134-a448-96a12eef7798.png)

![grafik](https://user-images.githubusercontent.com/8291561/228290749-d7cf7738-3f7b-45ca-8105-f908cf9a42e0.png)

![grafik](https://user-images.githubusercontent.com/8291561/228290773-d18c0187-8642-4b76-8f36-eb05b23250e1.png)

Using extension v1.4.7

**Comment by gquerret** [comment]
Syntax highlight documentation can be found here: https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide
In short, the ABL plugin is using the existing TextMate grammar: https://github.com/chriscamicas/abl-tmlanguage
There are many flaws in it, but I'm not sure they can be fixed with a regexp-style parser. Using semantic highlighting with the language server might be the solution, but that won't implemented in a near future.

You can improve the TM grammar if you want ; that will also benefit other code editors.

**Comment by PeterJudgeZA** [comment]
> Using semantic highlighting with the language server might be the solution, but that won't implemented in a near future.

I didn't realise that the TextMate grammer used regexs.  The semantic highlighting option looks like a significantly better approach.
